### ISSUE TITLE
Some filenames issues

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [Jean-Baptiste-Camps/Wauchier_stylo#2]
Noms de textes ne sont pas tous les mêmes dans nos données de ref et dans les données Kraken ou Students:
Ex. noms de nos fichiers jusque là:
```
[1] "17_Ano_Leg-B_Ma_Fe_Vie_Agathe"    "18_Ano_Leg-B_Ma_Fe_Vie_Luce"
[3] "19_Ano_Leg-B_Ma_Fe_Vie_Agnes"     "20_Ano_Leg-B_Ma_Fe_Vie_Felicite" 
[5] "21_Ano_Leg-B_Ma_Fe_Vie_Christine" "22_Ano_Leg-B_Ma_Fe_Vie_Cecile"
[7] "52_Ano_Leg-C_Co_NA_Vie_Fursi"
```

Noms dans Kraken:

```
"17_Ano_Leg-B_Ma_Ho_Vie_Agathe"
 "18_Ano_Leg-B_Ma_Ho_Vie_Luce"      "19_Ano_Leg-B_Ma_Ho_Vie_Agnes"
 "20_Ano_Leg-B_Ma_Ho_Vie_Felicite"  "21_Ano_Leg-B_Ma_Ho_Vie_Christine"
 "22_Ano_Leg-B_Ma_Ho_Vie_Cecile"   "52_Ano_Leg-C_Co_NA_Vie_Forsin"
```

Et avec l'autre, noms dans nos fichiers: 

```
"05_Ano_Leg-A_Ap_NA_Vie_Jacques"
```

Noms dans Students

```
"05_y_Leg-_A_Aptr_Vie"
[8] "Item_Aut_Leg-Légendier_Cl_soTitreRaccourci"
```

**Comment by Jean-Baptiste-Camps** [comment]
@PonteIneptique

**Comment by Jean-Baptiste-Camps** [comment]
@PonteIneptique : je ne sais pas si je rate quelque chose, mais j'ai l'impression que le fichier infra n'est pas ce qu'il doit être (juste une colonne de fréquence):

https://github.com/Jean-Baptiste-Camps/Wauchier_stylo/blob/master/data/transkr_student_raw_char3grams.csv

**Comment by PonteIneptique** [comment]
Crap. Cela dit tu as les données, tu dois pouvoir régénérer :)

**Comment by Jean-Baptiste-Camps** [comment]
Fait, je l'envoie.

**Comment by Jean-Baptiste-Camps** [comment]
Ouais, sauf que il y a encore un nom de fichier qui n'est pas le bon:

05_y_Leg-_A_Ap__tr_Vie.txt

Je recorrige ça.

**Comment by Jean-Baptiste-Camps** [comment]
Il manque quasi tout Antechrist dans les données des étudiants.
